steps:
  # 1. Build Backend Docker Image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - '$_LOCATION-docker.pkg.dev/$PROJECT_ID/$_REPO_NAME/backend:$COMMIT_SHA'
      - '-t'
      - '$_LOCATION-docker.pkg.dev/$PROJECT_ID/$_REPO_NAME/backend:latest'
      - './backend'
    id: 'build-backend'

  # 2. Build Frontend Docker Image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - '$_LOCATION-docker.pkg.dev/$PROJECT_ID/$_REPO_NAME/frontend:$COMMIT_SHA'
      - '-t'
      - '$_LOCATION-docker.pkg.dev/$PROJECT_ID/$_REPO_NAME/frontend:latest'
      - './frontend'
    id: 'build-frontend'

# Push built images to Artifact Registry
images:
  - '$_LOCATION-docker.pkg.dev/$PROJECT_ID/$_REPO_NAME/backend:$COMMIT_SHA'
  - '$_LOCATION-docker.pkg.dev/$PROJECT_ID/$_REPO_NAME/backend:latest'
  - '$_LOCATION-docker.pkg.dev/$PROJECT_ID/$_REPO_NAME/frontend:$COMMIT_SHA'
  - '$_LOCATION-docker.pkg.dev/$PROJECT_ID/$_REPO_NAME/frontend:latest'

substitutions:
  _LOCATION: 'us-central1'
  _REPO_NAME: 'chw-repo'

options:
  logging: CLOUD_LOGGING_ONLY
